plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.proinfowriter'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.proinfowriter"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.2'
}
